services:
  app:
    build: ./services/api_bus
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - parser-service
      - ai-service
    volumes:
      - ./services/api_bus:/app

    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    image: pgvector/pgvector:pg16
    container_name: my_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./services/api_bus/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  parser-service:
    build: ./services/parser
    ports:
      - "5001:5001"

    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./services/parser:/app

  ai-service:
    build: ./services/ai_model
    ports:
      - "5002:5002"

    env_file:
      - .env

    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./services/ai_model:/app
volumes:
  postgres_data: