services:
  app:
    build: ./services/api_bus
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - parser
      - ai-service
    volumes:
      - ./services/api_bus:/app

    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: pgvector/pgvector:pg16
    container_name: data_base
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parser:
    build: ./services/parser
    ports:
      - "5001:5001"

    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./services/parser:/app

  front:
    build: ./front
    ports:
      - "4173:4173"

    env_file:
      - .env

    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.vite
    stdin_open: true
    tty: true

  ai-service:
    build: ./services/ai_model
    ports:
      - "5002:5002"

    env_file:
      - .env

    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./services/ai_model:/app
      - ./services/ai_model/models:/app/models
volumes:
  postgres_data: